name = "Arcanus"
filename = "arcanus-1.25.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3591/193/arcanus-1.25.jar"
hash-format = "murmur2"
hash = "413683293"

[update]
[update.curseforge]
file-id = 3591193
project-id = 517833
