name = "Caracal Mod (Fabric/Forge)"
filename = "caracal-1.18-1.3.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3724/177/caracal-1.18-1.3.8.jar"
hash-format = "murmur2"
hash = "1246462067"

[update]
[update.curseforge]
file-id = 3724177
project-id = 486505
