name = "Comforts (Fabric)"
filename = "comforts-fabric-1.0.3-1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3681/443/comforts-fabric-1.0.3-1.18.1.jar"
hash-format = "murmur2"
hash = "2924263059"

[update]
[update.curseforge]
file-id = 3681443
project-id = 433539
