name = "Crawl (Fabric)"
filename = "crawl-0.10.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3600/898/crawl-0.10.1.jar"
hash-format = "murmur2"
hash = "1296461299"

[update]
[update.curseforge]
file-id = 3600898
project-id = 314579
