name = "DeepslateCutting"
filename = "deepslatecutting-1.18.1-1.3.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3648/247/deepslatecutting-1.18.1-1.3.1.jar"
hash-format = "murmur2"
hash = "2432009234"

[update]
[update.curseforge]
file-id = 3648247
project-id = 504899
