name = "Enhanced Attack Indicator"
filename = "enhanced_attack_indicator-1.0.3+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3728/272/enhanced_attack_indicator-1.0.3+1.18.jar"
hash-format = "murmur2"
hash = "798072607"

[update]
[update.curseforge]
file-id = 3728272
project-id = 446173
