name = "FallingTree (Forge&Fabric)"
filename = "FallingTree-1.18.1-3.2.0b1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3604/824/FallingTree-1.18.1-3.2.0b1.jar"
hash-format = "murmur2"
hash = "553292600"

[update]
[update.curseforge]
file-id = 3604824
project-id = 349559
