name = "Firework Frenzy"
filename = "fireworkfrenzy-1.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3661/317/fireworkfrenzy-1.8.jar"
hash-format = "murmur2"
hash = "4171554775"

[update]
[update.curseforge]
file-id = 3661317
project-id = 520310
