name = "More Axolotl Variants Mod"
filename = "mavm-fabric-1.18.1-1.0.7a.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3590/362/mavm-fabric-1.18.1-1.0.7a.jar"
hash-format = "murmur2"
hash = "1556367093"

[update]
[update.curseforge]
file-id = 3590362
project-id = 498797
