name = "MaxVar reap "
filename = "mcf-reap-1.7.0-1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3586/960/mcf-reap-1.7.0-1.18.1.jar"
hash-format = "murmur2"
hash = "859729614"

[update]
[update.curseforge]
file-id = 3586960
project-id = 368705
