name = "MC Dungeons Armors"
filename = "mcda-2.0.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3736/30/mcda-2.0.5.jar"
hash-format = "murmur2"
hash = "3773846049"

[update]
[update.curseforge]
file-id = 3736030
project-id = 426206
