name = "MC Dungeons Artifacts"
filename = "mcdar-1.4.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3759/832/mcdar-1.4.6.jar"
hash-format = "murmur2"
hash = "415299854"

[update]
[update.curseforge]
file-id = 3759832
project-id = 476788
