name = "MC Dungeons Weapons"
filename = "mcdw-4.3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3759/746/mcdw-4.3.0.jar"
hash-format = "murmur2"
hash = "539461153"

[update]
[update.curseforge]
file-id = 3759746
project-id = 407311
