name = "Tom's Simple Storage Mod (Fabric)"
filename = "toms_storage-1.18.1-backport-1.3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3708/452/toms_storage-1.18.1-backport-1.3.0.jar"
hash-format = "murmur2"
hash = "529305567"

[update]
[update.curseforge]
file-id = 3708452
project-id = 396826
