name = "Villager Names (Fabric)"
filename = "villagernames-1.18.1-3.0.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3659/772/villagernames-1.18.1-3.0.3.jar"
hash-format = "murmur2"
hash = "512216444"

[update]
[update.curseforge]
file-id = 3659772
project-id = 416379
