name = "Wandering Collector"
filename = "wanderingcollector-1.1.1+mc1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3707/255/wanderingcollector-1.1.1+mc1.18.2.jar"
hash-format = "murmur2"
hash = "2767705617"

[update]
[update.curseforge]
file-id = 3707255
project-id = 443476
